# Generated by Django 3.1.7 on 2021-04-05 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilesusers',
            old_name='idCompany',
            new_name='idUser',
        ),
    ]
