# Generated by Django 3.1.7 on 2021-04-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0002_auto_20210405_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataExercises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCourse', models.IntegerField()),
                ('idStudent', models.IntegerField()),
                ('idExerciseSelected', models.IntegerField()),
                ('idVehicleSelected', models.IntegerField()),
                ('speedReq', models.IntegerField()),
                ('v1', models.FloatField()),
                ('v2', models.FloatField()),
                ('v3', models.FloatField()),
                ('penalties', models.IntegerField()),
            ],
        ),
    ]
