# Generated by Django 3.1.7 on 2021-04-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0003_dataexercises'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFinalExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCourse', models.IntegerField()),
                ('idStudent', models.IntegerField()),
                ('idVehicleSelected', models.IntegerField()),
                ('stressLevel', models.IntegerField()),
                ('revSlalom', models.FloatField(blank=True, null=True)),
                ('slalom', models.FloatField(blank=True, null=True)),
                ('laneChange', models.FloatField(blank=True, null=True)),
                ('cones', models.IntegerField()),
                ('gates', models.IntegerField()),
                ('time', models.FloatField()),
            ],
        ),
    ]
