# Generated by Django 3.1.7 on 2021-03-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0003_auto_20210225_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('fulldate', models.CharField(max_length=100)),
                ('vehicle', models.CharField(default='empty', max_length=100)),
                ('snor', models.CharField(default='empty', max_length=100)),
                ('spoce', models.CharField(default='empty', max_length=100)),
                ('saoep', models.CharField(default='empty', max_length=100)),
                ('saovc', models.CharField(default='empty', max_length=100)),
                ('sfpl', models.CharField(default='empty', max_length=100)),
                ('lnor', models.CharField(default='empty', max_length=100)),
                ('lpoce', models.CharField(default='empty', max_length=100)),
                ('laoep', models.CharField(default='empty', max_length=100)),
                ('laovc', models.CharField(default='empty', max_length=100)),
                ('lfpl', models.CharField(default='empty', max_length=100)),
            ],
        ),
    ]
