# Generated by Django 3.1.7 on 2021-03-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0004_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('fulldate', models.CharField(max_length=100)),
                ('countLnCh', models.FloatField()),
                ('countSlalom', models.FloatField()),
                ('passedLnCh', models.FloatField()),
                ('passedSlalom', models.FloatField()),
                ('avScoreLnCh', models.FloatField()),
                ('avScoreSlalom', models.FloatField()),
                ('startScoreLnCh', models.FloatField()),
                ('startScoreSlalom', models.FloatField()),
                ('endScoreLnCh', models.FloatField()),
                ('endScoreSlalom', models.FloatField()),
                ('lnChPassed', models.FloatField()),
                ('slalomPassed', models.FloatField()),
            ],
        ),
    ]
