# Generated by Django 3.1.7 on 2021-04-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0004_datafinalexercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclesselected',
            name='csvLoadedDataExercise',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclesselected',
            name='csvLoadedDataFinalExercise',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
