# Generated by Django 3.1.7 on 2021-03-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0005_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('fulldate', models.DateTimeField()),
                ('cardId', models.IntegerField()),
                ('stress', models.IntegerField()),
                ('revSlalom', models.CharField(max_length=100)),
                ('revPc', models.FloatField()),
                ('slalom', models.FloatField()),
                ('lnCh', models.FloatField()),
                ('cones', models.IntegerField()),
                ('gates', models.IntegerField()),
                ('fTime', models.CharField(max_length=100)),
                ('finalResult', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='count',
            name='fulldate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='fulldate',
            field=models.DateTimeField(),
        ),
    ]
