# Generated by Django 3.1.7 on 2021-04-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0005_auto_20210407_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='gender',
            field=models.CharField(default='M', max_length=100),
            preserve_default=False,
        ),
    ]
