# Generated by Django 3.1.7 on 2021-03-10 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0006_auto_20210310_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalexercise',
            old_name='cardId',
            new_name='carId',
        ),
    ]
