# Generated by Django 3.1.7 on 2021-04-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0006_students_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='available',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
