# Generated by Django 3.1.7 on 2021-03-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0007_auto_20210310_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('fulldate', models.DateTimeField()),
                ('comment', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('fulldate', models.DateTimeField()),
                ('pcExercise', models.FloatField()),
                ('pcVehicle', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SlalomAvg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('fulldate', models.DateTimeField()),
                ('vehiclePcAvgLnCh', models.FloatField()),
                ('vehiclePcAvgSlalom', models.FloatField()),
            ],
        ),
    ]
