# Generated by Django 3.1.7 on 2021-05-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0008_courses_excelloaded'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFinalExercisePc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCourse', models.IntegerField()),
                ('idStudent', models.IntegerField()),
                ('rev', models.FloatField()),
                ('slalom', models.IntegerField()),
                ('laneChange', models.IntegerField()),
                ('cones', models.IntegerField()),
                ('gates', models.IntegerField()),
                ('finalTime', models.FloatField()),
                ('finalResult', models.FloatField()),
            ],
        ),
    ]
