# Generated by Django 3.1.7 on 2021-03-23 19:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0008_comments_course_slalomavg'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='exercise',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
