# Generated by Django 3.1.7 on 2021-05-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0009_datafinalexercisepc'),
    ]

    operations = [
        migrations.CreateModel(
            name='PPR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCourse', models.IntegerField()),
                ('idStudent', models.IntegerField()),
                ('PPR', models.IntegerField()),
                ('eventDate', models.DateTimeField()),
            ],
        ),
    ]
