# Generated by Django 3.1.7 on 2021-05-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0012_studentrecords'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppr',
            name='idCompany',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
