# Generated by Django 3.1.7 on 2021-05-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0013_ppr_idcompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppr',
            name='idCountry',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
