# Generated by Django 3.1.7 on 2021-05-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0014_ppr_idcountry'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalExercisesSelected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCourse', models.IntegerField()),
                ('idExercise', models.IntegerField()),
                ('chord', models.IntegerField()),
                ('mo', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='exercises',
            name='chord',
        ),
        migrations.RemoveField(
            model_name='exercises',
            name='mo',
        ),
        migrations.AddField(
            model_name='exercisesselected',
            name='chord',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercisesselected',
            name='mo',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
