# Generated by Django 3.1.7 on 2021-07-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0015_auto_20210526_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='idCountry',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
